### ISSUE TITLE
[Tech] Reasearch and come up with a plan for CI/CD pipelines

### ISSUE THREAD

**Issue by thiago-porto25** [thiago-porto25/chat-random#8]
After the research we will leave in the comments what was chosen.

**Comment by thiago-porto25** [comment]
# What was agreed upon

## CI
For both repos CI will follow a simple pattern where when a pull requst is created the CI pipeline will run and if the PR is approved and CI runs without errors the branch can be merged.

## CD
Since we chose Vercel for deployment of the App the CD pipeline for the main Repo is handled by them. For the other Repo we will use Github Actions to publish the package to NPM when a new release is created. Here's an example of how the yaml file will look like:
```yaml
name: Publish package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          yarn: true
          registry-url: https://registry.npmjs.org
      - name: Install dependencies & Build
        run: yarn && yarn build
      - name: Publish packages on NPM
        run: yarn run publish
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
```
